"""
Django settings for pios_system project.

Generated by 'django-admin startproject' using Django 4.1.5.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os
from decouple import config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-d&lf8i4-puu$8#+&7qpl^!(__q$&qx@!ovl7a8ij^^7#tg$v56"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

#CHANGED ALLOWED HOST TO VERCEL APPS "REMEMBER TO CHANGE IF ROLLBACK"
ALLOWED_HOSTS = ['.vercel.app']

INSTALLED_APPS = [
    # soft delete
    'safedelete',

    # name of the store (this is an app)
    'customerportal',

    # improved admin dashbaord frontend
    'jazzmin',

    'ckeditor',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Cart
    'basket',

    # User Accounts
    'account',

    # django honeypot will send email
    'admin_honeypot',

    # icons
    'fontawesomefree',

    # handling orders
    'orders',
]


# middleware -> basically security or protection before transforming data
MIDDLEWARE = [
    # third-party app
    'whitenoise.middleware.WhiteNoiseMiddleware',

    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'pios_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], #location of all templates from all apps
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'customerportal.context_processors.categories',
                'basket.context_processors.basket',
            ],
        },
    },
]

WSGI_APPLICATION = 'pios_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

STATICFILES_DIRS = ( os.path.join(BASE_DIR, 'static'), )

STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':"pios_database",
        'USER':"postgres",
        'PASSWORD':"admin123",
        "HOST":"database-1.cgrlqxu4fho5.ap-northeast-1.rds.amazonaws.com",
        "PORT":"5432"
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


# HTTPS settings
# settings to make http to https during production live
# DO NOT UNCOMMENT
# SESSIONG_COOKIE_SECURE = True
# CSRF_COOKIE_SECURE = True
# SECURE_SSL_REDIRECT = True

# Basket session ID
BASKET_SESSION_ID = 'basket'

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# location of our static files/ ex. CSS javascript
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS=[
    os.path.join(BASE_DIR,'static')
]

# all image related static or submitted from the admin dashboard
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media/')

# Custom user model (new login for the admin dashboard)
AUTH_USER_MODEL = 'account.UserBase'
LOGIN_REDIRECT_URL = '/account/dashboard'
LOGIN_URL = '/account/login/'

# # django honeypot email alert on unauthorized access
ADMINS = (
    ('admin', '201901245@iacademy.edu.ph'),
)

# Gmail or your service email config
EMAIL_HOST='smtp.gmail.com'
EMAIL_HOST_USER = 'sihiacafe@gmail.com' #-> temporary disabled to prevent sa personal email ko
EMAIL_HOST_PASSWORD='ooslewqlziypwrfr'
# -> needs to be generated via gmail manageaccounts/security/app
# two authentication must be enabled and app password must be generated
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'


JAZZMIN_SETTINGS = {
    # title of the window (Will default to current_admin_site.site_title if absent or None)
    "site_title": "Sihia Cafe Admin",

    # Title on the login screen (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_header": "Sihia Cafe",

    # Title on the brand (19 chars max) (defaults to current_admin_site.site_header if absent or None)
    "site_brand": "Sihia Cafe",

    # Logo to use for your site, must be present in static files, used for login form logo (defaults to site_logo)
    "login_logo": "../media/business-icons/business-logoLogin.png",

    # Logo to use for your site, must be present in static files, used for brand on top left
    "site_logo": "../media/business-icons/business-logoLogin.png",

    # Logo to use for login form in dark themes (defaults to login_logo)
    "login_logo_dark": "../media/business-icons/business-logoLogin.png",

    # CSS classes that are applied to the logo above
    "site_logo_classes": "img-circle",

    # Relative path to a favicon for your site, will default to site_logo if absent (ideally 32x32 px)
    "site_icon": "../media/business-icons/business-logoIcon.png",

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Sihia Cafe Dashboard",

    # Copyright on the footer
    "copyright": "Sihia Cafe 2023",

}
